---
title: "TBI Preliminary Results"
author: "Eric Czech"
date: "November 22, 2015"
output: html_document
---

PbtO2 preliminary results.

```{r, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(rstan)
library(dplyr)
library(ggplot2)
library(reshape2)
e <- new.env()
post <- load('~/data/pbto2/export/posterior_120hr_tsa.Rdata', envir = e)
post <- e$posterior
post <- rstan::extract(post)

source('~/repos/portfolio/demonstrative/R/pbto2/common.R')

d <- read.csv('~/data/pbto2/export/data_model_input_120hr_tsa.csv', stringsAsFactors=F)
features <- c('pbto2', 'age', 'marshall', 'gcs', 'sex')

beta.post <- compute.var.posteriors(d, post)
```

Estimate for most import PbtO2 threshold (between 5 and 30):

```{r, echo=FALSE}
beta.post %>% 
  ggplot(aes(x=pbto2_cp)) + geom_density(fill='red', alpha=.5) + 
  theme_bw() + ggtitle('Pbto2 Cutpoint Estimates') + 
  xlab('Pbto2 Cutoff')
```

Estimate for most import PbtO2 threshold (between 5 and 30):

```{r, echo=FALSE}
beta.post$time_cp %>% table %>% melt %>% setNames(c('time_cp', 'ct')) %>% 
  mutate(time_cp = time_cp / 1440) %>%
  ggplot(aes(x=factor(time_cp), y=ct)) + geom_bar(stat='identity') + 
  theme_bw() + ggtitle('Time Cutpoint Estimates') + 
  xlab('Time (days)') + ylab('Frequency')
```

Coefficient Estimates (95% Credible Intervals):

```{r, echo=FALSE}
plot.beta.post(beta.post)
```

PbtO2 Coefficient Posterior Distributions:

```{r, echo=FALSE}
plot.pbto2.coef(beta.post) 
```

PbtO2 Cutpoint vs Coefficient: 

```{r, echo=FALSE}
beta.post %>% 
  ggplot(aes(x=pbto2_cp, y=pbto2_lo)) + geom_jitter() +
  theme_bw() + xlab('PbtO2 Cutpoint') + ylab('PbtO2 Coefficient (below cutpoint)')
```
